#!/bin/bash
set -e

defaults(){
	target_ip="Rpi3Dev.local" && echo "default target ip = $target_ip"
#	target_ip="192.168.0.58" && echo "default target ip = $target_ip"
	login="pi"&& echo "default login name = $login"
	passwd="raspberry" && echo "default password = $passwd"
	ssh_keyname="PiMaker@NUC" && echo "default ssh_keyname = $ssh_keyname"
	ssh_key_path="/home/pimaker/.ssh/" && echo "default ssh_key_path = $ssh_key_path"
}

enableRootLogin () {
	sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
	sudo service ssh restart
}

change_defaults () {
#TODO
echo ""
}

ssh_key_copy(){
options="$@" 

	ssh-copy-id $options -i $ssh_key_path$ssh_keyname $login@$target_ip || \
	ssh-keygen -f "/home/pimaker/.ssh/known_hosts" -R $target_ip || \
	echo "copyKey error"
}

defaults
ssh_key_copy
