#!/bin/bash

# https://forum.snapcraft.io/t/running-snaps-on-wsl2-insiders-only-for-now/13033
# https://gist.github.com/stowler/9921780 # VcXserver cmd-s
# remove "UNC paths are not supported" message: 2>nul or
# HKEY_CURRENT_USER\Software\Microsoft\Command Processor  add the value DisableUNCCheck REG_DWORD and set the value to 0 x 1 (Hex).

# exports:
sed -i '/^export /d;/cmd.exe/d' ~/.bashrc >/dev/null
echo >> ~/.bashrc
ipconfig.exe | sed '/IPv4/!d;s/.* \: /export DISPLAY=/;s/.$/:0/' | sed -n '1p' >> ~/.bashrc
echo export LIBGL_ALWAYS_INDIRECT=1 >> ~/.bashrc
#sudo mkdir -p /run/user/1000
#echo export XDG_RUNTIME_DIR=/run/user/1000 >> ~/.bashrc
#echo export RUNLEVEL=3 >> ~/.bashrc
# echo 'cmd.exe /c /V:ON "( set PATH=%PATH%;%ProgramFiles%\VcXsrv && cmd.exe /c /V:ON start vcxsrv.exe -wgl -dpi auto -ac -multiwindow -silent-dup-error )"' >> ~/.bashrc
cmd.exe /c start vcxsrv.exe -wgl -dpi auto -ac -multiwindow -silent-dup-error 2>nul
. ~/.bashrc #2>/dev/null

#echo $USER ALL=\(ALL\) NOPASSWD: ALL | sudo tee /etc/sudoers.d/$USER
sudo apt update #&& sudo apt -y upgrade
sudo mkdir -p /run/sendsigs.omit.d/rpcbind
sudo apt install -y nfs-common zenity
sudo service rpcbind start
DIR_TO_MOUNT='/mnt/LinuxData/OF'
sudo mkdir -pv ${DIR_TO_MOUNT}
# LABEL=cloudimg-rootfs   /                       ext4    defaults        0 0
FSTAB_ENTRY="NUC:${DIR_TO_MOUNT} ${DIR_TO_MOUNT} nfs4 defaults 0 0"
sudo sed -i "/^NUC:/d;s/$/\n${FSTAB_ENTRY//\//\\/}/" /etc/fstab
sudo mount -a
mountpoint /mnt/LinuxData/OF && echo HURRAH! || echo "BASSZAMEG!"

# sudo sed -i 's/^#Port 22/Port 2222/' /etc/ssh/sshd_config
# ;s/#PubkeyAuthentication yes/PubkeyAuthentication yes/